version: "3"

services:
  nats-server:
    image: nats:2.10.24

  main-gateway:
    build: 
      context: ./main-gateway
      dockerfile: dockerfile.prod
    # image: main-gateway
    image: us-central1-docker.pkg.dev/store-ms-448722/image-registry/main-gateway
    ports:
      - ${MAIN_GATEWAY_PORT}:${MAIN_GATEWAY_PORT}
    environment:
      - PORT=${MAIN_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    # image: auth-ms
    image: us-central1-docker.pkg.dev/store-ms-448722/image-registry/auth-ms
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    # image: products-ms
    image: us-central1-docker.pkg.dev/store-ms-448722/image-registry/products-ms
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - DATABASE_URL=${ORDERS_DATABASE_URL}
    # image: orders-ms
    image: us-central1-docker.pkg.dev/store-ms-448722/image-registry/orders-ms
    environment:
      - PORT=${ORDERS_MS_PORT}
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: us-central1-docker.pkg.dev/store-ms-448722/image-registry/payments-ms
    ports:
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}