apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: main-gateway
  name: main-gateway
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: main-gateway
  type: NodePort
status:
  loadBalancer: {}
